### ISSUE TITLE
词云图片背景为空白

### ISSUE THREAD

**Issue by ghost** [pcrbot/GroupWordCloudGenerator#1]
mask参数未生效，不知道是否是WordCloud版本问题

![image](https://user-images.githubusercontent.com/65025615/129066668-199cfcb0-5017-4805-bd68-1c2ba95b2f3f.png)

**Comment by A-kirami** [comment]
效果就是空白的，最后词云密度大了之后会接近那张图片的样子（类似字符画

**Comment by ghost** [comment]
原来如此，是我没看明白(///▽///)
